- name: INSTALLING RABBITMQ
  shell: "{{ item }}"
  loop:
  - "curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash"
  - "curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash"
  - dnf install rabbitmq-server -y

- name: ENABE AND START RABBITMQ
  service:
    name: rabbitmq-server
    state: started
    enabled: true

- name: ROBOSHOP USER CREATION
  shell: "{{ item }}" 
  loop:
  - "rabbitmqctl add_user {{roboshop_user}} {{roboshop_pass}}"
  - rabbitmqctl set_permissions -p / {{roboshop_user}} ".*" ".*" ".*" 