- name: Creating roboshop user
  user:
    name: roboshop

- name: Creating App directory
  file:
    path: /app
    state: absent

- name: Creating App directory
  file:
    path: /app
    state: directory  

- name: Downloading App Code
  get_url:
    url: "https://roboshop-builds.s3.amazonaws.com/{{ component }}.zip"
    dest: /tmp

- name: unzipping app copde
  unarchive:
    src: "/tmp/{{ component }}.zip"
    dest: /app
    remote_src: yes