- name: copying {{ component }} service file
  template:
    src: "{{ component }}.service.j2"
    dest: "/etc/systemd/system/{{ component }}.service"
 


# - name: RELOAD SYSTEMD DAEMON of {{component}}
#   systemd:
#     name: "{{component}}"
#     enabled: yes


- name: deamon realod and start
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: RELOAD SYSTEMD DAEMON of {{component}}
  service:
    name: "{{component}}"
    state: restarted
    enabled: yes    
