- name: copying {{ component }} service file
  template:
    src: "{{ component }}.service.j2"
    dest: "/etc/systemd/system/{{ component }}.service"
 


# - name: RELOAD SYSTEMD DAEMON of {{component}}
#   systemd:
#     name: "{{component}}"
#     enabled: yes
 

- name: RELOAD SYSTEMD DAEMON of {{component}}
  systemd:
    name: "{{component}}"
    daemon_reloaded: yes
    state: restarted
    enabled: yes    
